name: compile

on:
  push:
    branches:
      - master

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed_files
        uses: tj-actions/changed-files@v44

      - name: Fetch old files
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: .gh-pages-temp
        continue-on-error: true

      - name: Prepare output directory with old files
        run: |
          mkdir -p out
          cp .gh-pages-temp/resume.pdf out/resume.pdf || true
          cp .gh-pages-temp/resume.html out/resume.html || true

      - name: Compile LaTeX to PDF (if changed)
        if: contains(steps.changed_files.outputs.all_changed_files, 'main.tex')
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: Setup Pandoc (if changed)
        if: contains(steps.changed_files.outputs.all_changed_files, 'main.tex')
        uses: pandoc/actions/setup@v1

      - name: Convert LaTeX to HTML with Pandoc (if changed)
        if: contains(steps.changed_files.outputs.all_changed_files, 'main.tex')
        run: pandoc main.tex -s -o out/resume.html

      - name: Copy static files and compiled PDF
        run: |
          if [ -f main.pdf ]; then
            cp ./main.pdf ./out/resume.pdf
          fi
          cp ./index.html ./out/index.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          folder: out
          token: ${{ secrets.DEPLOY_TOKEN }}
          clean: true
          single-commit: true