name: compile

on:
  push:
    branches:
      - master

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: Copy
        run: |
          mkdir out
          cp ./main.pdf ./out/resume.pdf
          cp ./index.html ./out/index.html
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume
          path: out/resume.pdf
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          folder: out
          token: ${{ secrets.DEPLOY_TOKEN }}
          clean: true
          single-commit: true