name: compile

on:
  push:
    branches:
      - master

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: Copy
        run: |
          mkdir out
          cp ./main.pdf ./out/resume.pdf
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: resume
          path: out/resume.pdf
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          BRANCH: gh-pages
          CLEAN: true
          SINGLE_COMMIT: true
          FOLDER: out
          GIT_CONFIG_NAME: github-actions[bot]
          GIT_CONFIG_EMAIL: github-actions[bot]@users.noreply.github.com