name: compile

on:
  push:
    branches:
      - master

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed_files
        uses: tj-actions/changed-files@v44

      - name: Fetch old files
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: .temp
        continue-on-error: true

      - name: Prepare output directory
        run: |
          mkdir -p out
          cp .temp/resume.pdf out/resume.pdf || true

      - name: Compile LaTeX to PDF (if changed)
        if: contains(steps.changed_files.outputs.all_changed_files, 'main.tex')
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: Copy static files
        run: |
          if [ -f main.pdf ]; then
            cp main.pdf out/resume.pdf
          fi
          cp public/* out/*

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          folder: out
          token: ${{ secrets.DEPLOY_TOKEN }}
          clean: true
          single-commit: true